# System size
N = 1000 # Number of grid points in x direction
nsteps = 100000 # Number of iteration steps

B_ext = -2.22 # External field [mT]
dmi_const = 0 # DMI constant [J/m²]

dx = 6 # Discretization length along x direction [nm]
dt = 0.0025 # Discretization time [ns]

xi = 20 # [nm]
sigma = 7 # [mT]

Ms = 9.1e5
Ku = 8.4e5
Aex = 1.4e-11
alpha = 0.27
Delta = 0.5e-9 # Film thickness [m]

print_frec = 100
resolution_along_x = 1000
calc_v_frec = 1

n_y_eta = 1000
write_eta_to_file = F
random_seed=12345

RUNOPT
<RAMPED_FIELD> = F # Not implemented yet
<FILE_PARTIONING> = F # Not implemented yet