# System size
N = 1000 # Number of grid points in x direction
nsteps = 5000 # Number of iteration steps
nsteps_relax = 1000 # Number of relaxation iteration steps with Bext=0
nsteps_at_ramp = 1000 # Number of steps per Bext value

B_ext = -2.22 # External field [mT]
dmi_const = 0 # DMI constant [J/m²]

dx = 6 # Discretization length along x direction [nm]
dt = 0.0025 # Discretization time [ns]

xi = 20 # [nm]
sigma = 7 # [mT]

start_with_noise = 0.0 # Start with random values for phi, 0 < phi[i] < value*2*pi
include_first_order = T # Include first order terms of demagnetization

Ms = 9.1e5
Ku = 8.4e5
Aex = 1.4e-11
alpha = 0.27
Delta = 0.5e-9 # Film thickness [m]

# Ramp parameters [can be anything if ramped field is false]
Bext_step = -0.01
Bext_end = -2.25 # Simulation ends at Bext_end for ramped version

print_frec = 100
resolution_along_x = 1000
calc_v_frec = 1

n_y_eta = 1000
write_eta_to_file = F
random_seed=12345

RUNOPT
<RAMPED_FIELD> = T
<FILE_PARTIONING> = F # Not implemented yet
